# Configuración del experimento Experimento1
experiment:
  name: "delta-lags-percentile" # Indica la features probadas
  tag: "0.1_150_03-04_G_Base" # "sampling_trials_from-to_feval" tag para indicar el tipo de experimento
  version: "0.0.6" # Version de código src
  debug: false
  sample_ratio: 0.1
  n_trials: 150
  n_init: 30 # Exploración de optuna.
  positive_classes: ["BAJA+1", "BAJA+2"] # Clase positiva durante training
  description: "Experimento Delta lags y percentiles, optimizando por ganancia, clase positiva durante training = (BAJA+1 y BAJA+2) Set de hiperparámetros B"
  experiments_path: "./experiments"
  data_path: "./data"
  raw_data_path: "./data/competencia_01_crudo.csv"
  result_path: "./results"
  commit: True
  seeds: [537919, 923347, 173629, 419351, 287887, 41, 42, 43, 44, 45]
  n_sends: 11500
hyperparameters:
  num_leaves:
    type: "int"
    min: 10
    max: 1200
  max_depth:
    type: "int"
    min: 3
    max: 12
  learning_rate:
    type: "float" 
    min: 0.01
    max: 0.3
  min_data_in_leaf:
    type: "int"
    min: 100
    max: 2000
  min_gain_to_split:
    type: "int"
    min: 0
    max: 5
  feature_fraction:
    type: "float"
    min: 0.5
    max: 1.0
  bagging_fraction:
    type: "float"
    min: 0.5
    max: 1.0
  num_boost_round:
    type: "int"
    min: 10000
    max: 10000
  early_stopping_rounds:
    type: "int"
    min: 50
    max: 50
data:
  train_months: [202103, 202104]
  test_month: None
  eval_month: 202106
weights:
  continue: 1
  BAJA+1: 1
  BAJA+2: 1

